### ISSUE TITLE
nic/stmmac: implement page_frag_alloc_align

### ISSUE THREAD

**Issue by trimpim** [genodelabs/genode-imx#12]
This method gets called when transferring data with scp.

**Comment by trimpim** [comment]
I did take the implementation from `nic/fec`. maybe this could even be added to the global `lx_emul`

**Comment by chelmuth** [comment]
You're right, we should consolidate the page_frag implementation. But in my opinion, we go for porting the original implementation from *mm/page_alloc.c*. It's only 3 C functions.

**Comment by skalk** [comment]
@trimpim sorry I somehow missed this issue. The funtion was now implicitly implemented when enabling STMMAC on the MNT pocket. Thereby I mark this issue as solved. I've preserved the discussion in a separate issue in genode-labs/genode#5385
