### ISSUE TITLE
gpu/imx8mq: fix decoupling schedule execution

### ISSUE THREAD

**Issue by cnuke** [genodelabs/genode-imx#6]
While adapting the driver I missed the local request handling, which renders the driver unusable.

**Comment by cnuke** [comment]
Commit [8feea03](https://github.com/cnuke/genode-imx/commit/8feea037d35f1c996f9f7665ae66c898ee417825) fixes the problem.

**Comment by nfeske** [comment]
Are you sure about adding the `printk` calls?

**Comment by cnuke** [comment]
No, I am afraid their inclusion was an accident, commit [c0511cd](https://github.com/cnuke/genode-imx/commit/c0511cdf2ec3a2de32b25b1fd05d514afe70349c) remedies that.
